
package com.stacktest.nextlab.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Nextlab_WSSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NextlabWSSoap {


    /**
     * 
     * @param pedido
     * @param token
     * @return
     *     returns com.stacktest.nextlab.soap.ResponseRealizarPedido
     */
    @WebMethod(operationName = "RealizarPedido", action = "http://tempuri.org/RealizarPedido")
    @WebResult(name = "RealizarPedidoResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RealizarPedido", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.RealizarPedido")
    @ResponseWrapper(localName = "RealizarPedidoResponse", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.RealizarPedidoResponse")
    public ResponseRealizarPedido realizarPedido(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "pedido", targetNamespace = "http://tempuri.org/")
        ReqPedido pedido);

    /**
     * 
     * @param tipo
     * @param numero
     * @param token
     * @return
     *     returns com.stacktest.nextlab.soap.ResponseConsultarResultados
     */
    @WebMethod(operationName = "ConsultarResultados", action = "http://tempuri.org/ConsultarResultados")
    @WebResult(name = "ConsultarResultadosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ConsultarResultados", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.ConsultarResultados")
    @ResponseWrapper(localName = "ConsultarResultadosResponse", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.ConsultarResultadosResponse")
    public ResponseConsultarResultados consultarResultados(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "tipo", targetNamespace = "http://tempuri.org/")
        int tipo,
        @WebParam(name = "numero", targetNamespace = "http://tempuri.org/")
        String numero);

    /**
     * 
     * @param codPac
     * @param token
     * @return
     *     returns com.stacktest.nextlab.soap.ResponseListadoOrdenes
     */
    @WebMethod(operationName = "ListadoOrdenesPorPaciente", action = "http://tempuri.org/ListadoOrdenesPorPaciente")
    @WebResult(name = "ListadoOrdenesPorPacienteResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListadoOrdenesPorPaciente", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.ListadoOrdenesPorPaciente")
    @ResponseWrapper(localName = "ListadoOrdenesPorPacienteResponse", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.ListadoOrdenesPorPacienteResponse")
    public ResponseListadoOrdenes listadoOrdenesPorPaciente(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "codPac", targetNamespace = "http://tempuri.org/")
        int codPac);

    /**
     * 
     * @param codAux
     * @param token
     * @return
     *     returns com.stacktest.nextlab.soap.ResponseListadoOrdenes
     */
    @WebMethod(operationName = "ListadoOrdenesPorPacienteAux", action = "http://tempuri.org/ListadoOrdenesPorPacienteAux")
    @WebResult(name = "ListadoOrdenesPorPacienteAuxResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ListadoOrdenesPorPacienteAux", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.ListadoOrdenesPorPacienteAux")
    @ResponseWrapper(localName = "ListadoOrdenesPorPacienteAuxResponse", targetNamespace = "http://tempuri.org/", className = "com.stacktest.nextlab.soap.ListadoOrdenesPorPacienteAuxResponse")
    public ResponseListadoOrdenes listadoOrdenesPorPacienteAux(
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token,
        @WebParam(name = "codAux", targetNamespace = "http://tempuri.org/")
        String codAux);

}
