
package com.stacktest.nextlab.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Nextlab_WS", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://genetrics.ddns.net:85/Nextlab_WS.asmx?WSDL")
public class NextlabWS
    extends Service
{

    private final static URL NEXTLABWS_WSDL_LOCATION;
    private final static WebServiceException NEXTLABWS_EXCEPTION;
    private final static QName NEXTLABWS_QNAME = new QName("http://tempuri.org/", "Nextlab_WS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://genetrics.ddns.net:85/Nextlab_WS.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NEXTLABWS_WSDL_LOCATION = url;
        NEXTLABWS_EXCEPTION = e;
    }

    public NextlabWS() {
        super(__getWsdlLocation(), NEXTLABWS_QNAME);
    }

    public NextlabWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), NEXTLABWS_QNAME, features);
    }

    public NextlabWS(URL wsdlLocation) {
        super(wsdlLocation, NEXTLABWS_QNAME);
    }

    public NextlabWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NEXTLABWS_QNAME, features);
    }

    public NextlabWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NextlabWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NextlabWSSoap
     */
    @WebEndpoint(name = "Nextlab_WSSoap")
    public NextlabWSSoap getNextlabWSSoap() {
        return super.getPort(new QName("http://tempuri.org/", "Nextlab_WSSoap"), NextlabWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NextlabWSSoap
     */
    @WebEndpoint(name = "Nextlab_WSSoap")
    public NextlabWSSoap getNextlabWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "Nextlab_WSSoap"), NextlabWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NEXTLABWS_EXCEPTION!= null) {
            throw NEXTLABWS_EXCEPTION;
        }
        return NEXTLABWS_WSDL_LOCATION;
    }

}
